apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-1
  namespace: prometheus
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data-pv-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-2
  namespace: prometheus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data-pv-2"
