apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: custom-serverless-runtime
  name: custom-serverless-runtime-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "services" ]
    verbs: [ "get", "list", "delete", "create","update", "watch", "patch" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "delete", "create","update", "watch", "patch" ]
