apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-serverless-apps-rb
  namespace: custom-serverless-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: custom-serverless-apps-role
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: custom-serverless
