apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: custom-serverless
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: frontend-ecr-secret
      containers:
        - name: frontend
          image: 444773651763.dkr.ecr.eu-central-1.amazonaws.com/custom-serverless-frontend:latest
          imagePullPolicy: Always
